version: "3"
services:
  dashboard:
    build: .
    container_name: dashboard-api
    env_file: .env
    links:
    - mongodb
    ports:
    - "8080:8080"
    command: /bin/sh -c "cd /usr/src/app  && npm start"

  mongodb:
    image: mongo
    container_name: dashboard-mongodb
    ports:
    - "27017:27017"
    volumes:
    - dbdata:/data/db

  configtxlator:
    image: zhigui/confiftxlator
    container_name: dashboard-configtxlator
    ports:
    - "7059:7059"

volumes:
  dbdata: {}
