version: "3"
services:
  dashboard-mongo:
    image: mongo
    container_name: dashboard-mongo
    ports:
    - "27017:27017"
    volumes:
    - dbdata:/data/db

  dashboard-configtxlator:
    image: zhigui/configtxlator
    container_name: dashboard-configtxlator
    ports:
    - "7059:7059"
    volumes:
    - /tmp/configtxlator/data:/work/data

volumes:
  dbdata: {}
