version: "3"
services:
#  nginx:
#    image: nginx
#    container_name: nginx
#    restart: always
#    volumes:
#      - ./nginx/nginx.conf.raw:/etc/nginx/nginx.conf.raw
#      - /etc/letsencrypt:/etc/nginx/cert
#    env_file: .env.sample
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#      - dashboard
#    command: /bin/sh -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/nginx.conf.raw > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  dashboard:
    image: dashboard
    build:
      context: .
    container_name: dashboard-api
    env_file: .env
    volumes:
      - ./.env:/usr/src/app/.env
    ports:
      - "8080:8080"
    command: /bin/sh -c "cd /usr/src/app  && npm start"
