version: "3"
services:
  dashboard:
    build: .
    container_name: dashboard-api
    env_file: .env
    volumes:
    - ./:/usr/src/app
    links:
    - mongodb
    ports:
    - "8080:8080"
    command: /bin/sh -c "cd /usr/src/app  && npm start"

  mongodb:
    image: mongo
    container_name: dashboard-mongo
    ports:
    - "27017:27017"
    volumes:
    - dbdata:/data/db

volumes:
  dbdata: {}
